disabled_rules:
  - trailing_comma
  - identifier_name
  - void_return
  - operator_whitespace
  - nesting
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure

line_length:
  warning: 100
  error: 120
  ignores_comments: true

function_body_length:
  - 50

excluded:
  - .build
  - Pods
  - Modules/.build
